# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-27 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

default_location = "port"
default_category = "art"

class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='descripion',
            field=models.TextField(default='Photographical Art At Its Best!'),
        ),
        migrations.AddField(
            model_name='photo',
            name='taken_by',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='default.jpg', height_field='height', upload_to='', width_field='width'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(default='111444666', on_delete=django.db.models.deletion.CASCADE, to='gallery.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.ForeignKey(default='111444666', on_delete=django.db.models.deletion.CASCADE, to='gallery.Location'),
            preserve_default=False,
        ),
    ]
